/*
 * This source file was generated by the Gradle 'init' task
 */
package mod.tang.dev;

public class App {
    public static void main(String[] args) {
        Algorithm algo = new Algorithm();

         
        Object[] graphDataJson = GraphReader.readJson(json);
        int[][] matrixJson = (int[][]) graphDataJson[0];
        boolean[] statusJson = (boolean[]) graphDataJson[1];
        

        String resultJson = algo.dijkstra(matrixJson, 50, 69);

        System.out.println(resultJson);
        PathChecker.checkPath(statusJson, resultJson);
    }
}