// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package mod.tang.dev;

// public class App {
// //     public static void main(String[] args) {
// //         Algorithm algo = new Algorithm();

// //         String json = """
// //         {
// //             "nodes": [
// //                 {
// //                 "isSpecial": true,
// //                 "x": 317.9117161602002,
// //                 "y": 479.9721869117013,
// //                 "label": "Big Intersect"
                
// //                 },
// //                 {
// //                 "isSpecial": true,
// //                 "x": 216.08061917849886,
// //                 "y": 268.23801574852945,
// //                 "label": "Chemical"
                
// //                 },
// //                 {
// //                 "isSpecial": false,
// //                 "x": 227.8781243166228,
// //                 "y": 305.49329513207874,
// //                 "label": "14"
                
// //                 },
// //                 {
// //                 "isSpecial": false,
// //                 "x": 145.91650967281436,
// //                 "y": 307.3560591012562,
// //                 "label": "15"
                
// //                 },
// //                 {
// //                 "isSpecial": false,
// //                 "x": 207.38373527634494,
// //                 "y": 402.0445427381461,
// //                 "label": "16"
                
// //                 },
// //                 {
// //                 "isSpecial": false,
// //                 "x": 177.27280437189853,
// //                 "y": 366.42034279485733,
// //                 "label": "17"
                
// //                 }
// //             ],
// //             "edges": [
// //                 { "node2Index": 2, "curved": false, "node1Index": 3 },
// //                 { "node2Index": 1, "curved": false, "node1Index": 2 },
// //                 { "node2Index": 4, "curved": false, "node1Index": 5 },
// //                 {
// //                 "node2Index": 5,
// //                 "curved": true,
// //                 "node1Index": 3,
// //                 "controlPoint": { "x": 134.34480185858172, "y": 339.813305772754 }
// //                 }
// //             ]
// //         }
// //         """; 

// //         Object[] graphDataJson = GraphReader.readJson(json);
// //         int[][] matrixJson = (int[][]) graphDataJson[0];
// //         boolean[] statusJson = (boolean[]) graphDataJson[1];
        

// //         String resultJson = algo.dijkstra(matrixJson, 50, 69);

// //         System.out.println(resultJson);
// //         PathChecker.checkPath(statusJson, resultJson);
// //     }

// //     private static void printMatrix(int[][] matrix) {
// //         for (int[] row : matrix) {
// //             for (int value : row) {
// //                 System.out.print((value == Integer.MAX_VALUE ? "-" : value) + "\t");
// //             }
// //             System.out.println();
// //         }
// //     }

// //     private static void printStatuses(int[] statuses) {
// //         for (int i = 0; i < statuses.length; i++) {
// //             System.out.println("Node " + i + " status: " + statuses[i]);
// //         }
// //     }
// // }